- name: Jenkins - Terraform + Ansible Integration
  hosts: jenkins_cicd
  become: yes
  tasks:

    - name: Update APT
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy Hello World page
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Hello World from Jenkins </h1>"
